# Generated by Django 3.1.3 on 2020-12-01 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_transaction_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_internal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.TextField(default='unknown'),
            preserve_default=False,
        ),
    ]
