# Generated by Django 3.1.4 on 2020-12-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.URLField(default='https://bank.ubnetdef.org/default-product-image.png'),
        ),
    ]
