# Generated by Django 3.1.5 on 2021-02-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_per_account',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
