# Generated by Django 3.2.8 on 2021-10-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
